export const GOVERNORATES: Record<string, string> = {
 cairo: "القاهرة",
 giza: "الجيزة",
 alexandria: "الإسكندرية",
 dakahlia: "الدقهلية",
 sharqia: "الشرقية",
 gharbia: "الغربية",
 monufia: "المنوفية",
 qalyubia: "القليوبية",
 beheira: "البحيرة",
 "kafr-elsheikh": "كفر الشيخ",
 damietta: "دمياط",
 "port-said": "بورسعيد",
 ismailia: "الإسماعيلية",
 suez: "السويس",
 "north-sinai": "شمال سيناء",
 "south-sinai": "جنوب سيناء",
 fayoum: "الفيوم",
 "beni-suef": "بني سويف",
 minya: "المنيا",
 assiut: "أسيوط",
 sohag: "سوهاج",
 qena: "قنا",
 luxor: "الأقصر",
 aswan: "أسوان",
 "red-sea": "البحر الأحمر",
 matrouh: "مطروح",
 "new-valley": "الوادي الجديد",
};

export const governorateName = (slug: string) => GOVERNORATES[slug] || slug;
